# Generated by Django 2.0.5 on 2018-05-23 05:02

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=11)),
                ('period', models.CharField(max_length=7)),
                ('calls', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='call'), size=None)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['source', 'period'], name='bills_bill_source_c97820_idx'),
        ),
    ]
