# Generated by Django 2.0.5 on 2018-05-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20180524_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='period',
            field=models.DateField(),
        ),
    ]
