# Generated by Django 2.0.5 on 2018-05-30 22:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20180524_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='calls',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total',
        ),
        migrations.AddField(
            model_name='bill',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'calls': [], 'total': 0}, verbose_name='bill metadata'),
            preserve_default=False,
        ),
    ]
