version: '3'

services:

    nginx:
        build: ./nginx
        volumes:
            - static:/srv/static
            - ./phonebillapi/docs/build:/srv/docs
        ports:
            - "80:80"
        links:
            - "web:web"
    db:
        image: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    web:
        build: ./phonebillapi
        command: python manage.py runserver 0:8000
        ports:
            - "8000:8000"
        depends_on:
            - db
        volumes:
            - ./phonebillapi:/srv/web
            - static:/srv/static

volumes:
    pgdata: {}
    static: {}
