# Generated by Django 2.0.5 on 2018-05-10 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(max_length=9, null=True)),
                ('destination', models.CharField(max_length=9, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='call',
            name='end_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phonebill.CallEnd'),
        ),
        migrations.AddField(
            model_name='call',
            name='start_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phonebill.CallStart'),
        ),
    ]
