# Generated by Django 2.0.5 on 2018-05-12 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='end_record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='phonebill.CallEnd'),
        ),
        migrations.AlterField(
            model_name='callstart',
            name='destination',
            field=models.CharField(default='XX9999999', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callstart',
            name='source',
            field=models.CharField(db_index=True, default='XX8888888', max_length=9),
            preserve_default=False,
        ),
    ]
