# Generated by Django 2.0.5 on 2018-05-15 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebill', '0003_auto_20180512_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ['-end_record__timestamp', '-start_record__timestamp']},
        ),
        migrations.AlterField(
            model_name='call',
            name='end_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phonebill.CallEnd'),
        ),
        migrations.AlterField(
            model_name='call',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='callend',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ended at'),
        ),
        migrations.AlterField(
            model_name='callstart',
            name='destination',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='callstart',
            name='source',
            field=models.CharField(db_index=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='callstart',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Started at'),
        ),
    ]
